name: Omniscient Shell CI

on:
  push:
    branches: [ main, develop, copilot/** ]
    paths:
      - 'omniscient-shell/**'
      - '.github/workflows/omniscient-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'omniscient-shell/**'

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: omniscient-shell/target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        working-directory: ./omniscient-shell
        run: cargo fmt --all -- --check

      - name: Run clippy
        working-directory: ./omniscient-shell
        run: cargo clippy --no-default-features --features kitty -- -D warnings

      - name: Build (minimal features)
        working-directory: ./omniscient-shell
        run: cargo build --no-default-features --features kitty

      - name: Run tests
        working-directory: ./omniscient-shell
        run: cargo test --no-default-features --features kitty

      - name: Build with WASM support
        working-directory: ./omniscient-shell
        run: cargo build --features wasm
        if: matrix.os == 'ubuntu-latest'

      - name: Test with WASM support
        working-directory: ./omniscient-shell
        run: cargo test --features wasm
        if: matrix.os == 'ubuntu-latest'

  build-release:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: omniscient-shell-linux-x64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: omniscient-shell-windows-x64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: omniscient-shell-macos-x64
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build release
        working-directory: ./omniscient-shell
        run: cargo build --release --no-default-features --features kitty --target ${{ matrix.target }}

      - name: Create artifact directory
        run: mkdir -p artifacts

      - name: Copy binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cp omniscient-shell/target/${{ matrix.target }}/release/omniscient-shell artifacts/${{ matrix.artifact }}
          cp omniscient-shell/target/${{ matrix.target }}/release/omni artifacts/${{ matrix.artifact }}-omni

      - name: Copy binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cp omniscient-shell/target/${{ matrix.target }}/release/omniscient-shell.exe artifacts/${{ matrix.artifact }}.exe
          cp omniscient-shell/target/${{ matrix.target }}/release/omni.exe artifacts/${{ matrix.artifact }}-omni.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: artifacts/*

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run security audit
        working-directory: ./omniscient-shell
        run: cargo audit

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov

      - name: Generate coverage
        working-directory: ./omniscient-shell
        run: cargo llvm-cov --no-default-features --features kitty --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./omniscient-shell/lcov.info
          fail_ci_if_error: false
